// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"github.com/Nyarum/brrraaa/core"
	"github.com/Nyarum/brrraaa/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewServer() (*server.Server, error) {
	config, err := core.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := core.NewDB(config)
	if err != nil {
		return nil, err
	}
	client, err := server.NewClient(db)
	if err != nil {
		return nil, err
	}
	serverServer := &server.Server{
		DB:     db,
		Client: client,
	}
	return serverServer, nil
}

// wire.go:

var providerSet = wire.NewSet(core.CoreSet, server.ServerSet)
