// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"github.com/Nyarum/brrraaa/providers/config"
	"github.com/Nyarum/brrraaa/providers/database"
	"github.com/Nyarum/brrraaa/server"
	"github.com/Nyarum/brrraaa/services/storage"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewServer() (*server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	databaseDatabase := database.NewDatabase(configConfig)
	userStorage := storage.NewUserStorage(databaseDatabase)
	serverServer := &server.Server{
		UserStorage: userStorage,
		Config:      configConfig,
	}
	return serverServer, nil
}

// wire.go:

var providerSet = wire.NewSet(server.ServerSet)
